# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAuthorization(object):
    def setupUi(self, DialogAuthorization):
        DialogAuthorization.setObjectName("DialogAuthorization")
        DialogAuthorization.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAuthorization)
        self.buttonBox.setGeometry(QtCore.QRect(20, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(DialogAuthorization)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 60, 191, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(DialogAuthorization)
        self.label.setGeometry(QtCore.QRect(100, 0, 181, 16))
        self.label.setObjectName("label")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(DialogAuthorization)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 90, 191, 21))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(DialogAuthorization)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 160, 191, 21))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(DialogAuthorization)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 190, 191, 21))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_2 = QtWidgets.QLabel(DialogAuthorization)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogAuthorization)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(DialogAuthorization)
        self.pushButton.setGeometry(QtCore.QRect(220, 70, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(DialogAuthorization)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 170, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(DialogAuthorization)
        self.buttonBox.accepted.connect(DialogAuthorization.accept)
        self.buttonBox.rejected.connect(DialogAuthorization.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAuthorization)

    def retranslateUi(self, DialogAuthorization):
        _translate = QtCore.QCoreApplication.translate
        DialogAuthorization.setWindowTitle(_translate("DialogAuthorization", "Authorization"))
        self.label.setText(_translate("DialogAuthorization", "Выберите ваш тип учетной записи"))
        self.label_2.setText(_translate("DialogAuthorization", "Админинстратор"))
        self.label_3.setText(_translate("DialogAuthorization", "Пользователь"))
        self.pushButton.setText(_translate("DialogAuthorization", "Вход"))
        self.pushButton_2.setText(_translate("DialogAuthorization", "Вход"))
