# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(764, 613)
        self.TableForEditDatabase = QtWidgets.QTableView(SettingsWindow)
        self.TableForEditDatabase.setGeometry(QtCore.QRect(9, 9, 731, 481))
        self.TableForEditDatabase.setObjectName("TableForEditDatabase")
        self.pushButton = QtWidgets.QPushButton(SettingsWindow)
        self.pushButton.setGeometry(QtCore.QRect(440, 570, 301, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(SettingsWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 570, 301, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.BackButton = QtWidgets.QPushButton(SettingsWindow)
        self.BackButton.setGeometry(QtCore.QRect(340, 570, 75, 31))
        self.BackButton.setObjectName("BackButton")

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Edit Database"))
        self.pushButton.setText(_translate("SettingsWindow", "Добавить"))
        self.pushButton_2.setText(_translate("SettingsWindow", "Удалить"))
        self.BackButton.setText(_translate("SettingsWindow", "Назад"))
